language: csharp
mono: none
dotnet: 3.0.0
dist: xenial
sudo: false
env:
    global:
        - DOTNET_CLI_TELEMETRY_OPTOUT: 1

script:
    - cd src/BitSkinsApi
    - dotnet restore
    - dotnet build StashBot.sln -c Release
