language: csharp
dotnet: 3.0.1
sudo: false

env:
    global:
        - DOTNET_CLI_TELEMETRY_OPTOUT: 1

script:
    - cd src
    - dotnet build StashBot.sln -c Release
    - dotnet test -c Release --no-build StashBotTest/StashBotTest.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

after_script:
        - bash <(curl -s https://codecov.io/bash)
